# Generated by Django 5.2.6 on 2025-12-02 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_image_propertyimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="ai_generated_description",
            field=models.TextField(
                blank=True, help_text="AI-generated property description"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="ai_generated_story",
            field=models.TextField(blank=True, help_text="AI-generated property story"),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_data",
            field=models.JSONField(
                blank=True, help_text="Full response from cadastral API", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="parcel_number",
            field=models.CharField(
                blank=True, help_text="Cadastral parcel number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="realman_data",
            field=models.JSONField(
                blank=True, help_text="Realman API response data", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="valuo_data",
            field=models.JSONField(
                blank=True, help_text="Valuation data from Valuo.cz API", null=True
            ),
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="agency_logos/"),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_agencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agencies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("initial_message", models.TextField()),
                (
                    "message_thread",
                    models.JSONField(
                        default=list,
                        help_text="Array of message objects: [{sender, message, timestamp}]",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("replied", "Agency Replied"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="properties.agency",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Credit Purchase"),
                            ("deduction", "Feature Usage"),
                            ("refund", "Refund"),
                            ("bonus", "Bonus Credits"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ai_text", "AI Text Generation"),
                            ("ai_advisor", "AI Advisor Chat"),
                            ("valuo_api", "Valuo.cz API"),
                            ("realman_api", "Realman API"),
                            ("other", "Other"),
                        ],
                        help_text="Feature that consumed credits (for deductions)",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for purchases/bonuses, negative for deductions",
                        max_digits=10,
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context (e.g., property_id, payment_id)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("inquiry", "Agency Inquiry"),
                            ("sale", "Sale Inquiry"),
                            ("notification", "Anniversary Notification"),
                            ("system", "System Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipients", models.JSONField(help_text="List of recipient emails")),
                ("subject", models.CharField(max_length=255)),
                (
                    "body_preview",
                    models.TextField(
                        help_text="First 500 chars of email body", max_length=500
                    ),
                ),
                ("full_body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "communication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.communication",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_emails",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyColumnPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visible_columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of visible column identifiers",
                    ),
                ),
                (
                    "column_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of column identifiers",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Column Preference",
            },
        ),
        migrations.CreateModel(
            name="AIAdvisorChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("predefined", "Pre-defined Prompt"),
                            ("freeform", "Free-form Question"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "predefined_prompt_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of pre-defined prompt if used (e.g., 'renovation_advice')",
                        max_length=100,
                    ),
                ),
                (
                    "user_message",
                    models.TextField(help_text="User's question or message"),
                ),
                ("ai_response", models.TextField(help_text="AI's response")),
                ("model_used", models.CharField(default="gpt-4o", max_length=50)),
                (
                    "cost_credits",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Credits charged for this chat",
                        max_digits=5,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "language",
                    models.CharField(
                        help_text="Language of the conversation", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_chats",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["property", "created_at"],
                        name="properties__propert_21c7a1_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="properties__user_id_a16270_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AITextGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_type",
                    models.CharField(
                        choices=[
                            ("description", "Property Description"),
                            ("story", "Property Story"),
                            ("marketing", "Marketing Text"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="User's input or property details"),
                ),
                ("generated_text", models.TextField()),
                ("model_used", models.CharField(default="gpt-4o", max_length=50)),
                (
                    "cost_credits",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Credits deducted for this generation",
                        max_digits=5,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "was_applied",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user applied this text to the property",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["property", "-created_at"],
                        name="properties__propert_68a833_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="properties__user_id_ebdaad_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["user", "status"], name="properties__user_id_14b160_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["agency", "status"], name="properties__agency__42c047_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="properties__user_id_12fc63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["transaction_type"], name="properties__transac_9ff372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["user", "email_type", "-created_at"],
                name="properties__user_id_78ef22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["property", "-created_at"],
                name="properties__propert_88ebb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["status"], name="properties__status_8314fd_idx"),
        ),
    ]
