# Generated by Django 5.2.6 on 2025-12-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Available credits for paid features",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="encryption_key_salt",
            field=models.CharField(
                blank=True,
                help_text="Salt for deriving encryption key in file mode",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("cs", "Czech")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="storage_mode",
            field=models.CharField(
                choices=[("cloud", "Cloud Storage"), ("file", "File Storage")],
                default="cloud",
                help_text="User's data storage preference",
                max_length=10,
            ),
        ),
    ]
